name: primeprof
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  http: ^1.3.0
  provider: ^6.0.0
  shared_preferences: ^2.5.2
  file_picker: ^9.0.0
  image_picker: ^1.1.2
  permission_handler: ^11.4.0
  path_provider: ^2.1.1
  intl: ^0.20.2
  camera: ^0.10.5+2
  open_file: ^3.3.2
  cupertino_icons: ^1.0.8
  flutter_native_splash: ^2.4.4
  flutter_local_notifications: ^18.0.1
  socket_io_client: ^3.0.2
  url_launcher: ^6.1.0
  flutter_pdfview: ^1.3.2
  googleapis: ^13.1.0
  googleapis_auth: ^1.4.1
  google_ml_kit: ^0.18.0
  flutter_markdown: ^0.7.7
  flutter_stripe: ^9.5.0
  flutter_secure_storage: ^9.2.2
  share_plus: ^10.0.3  # Mise à jour vers 11.0.0
  clipboard: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/img.png
    - assets/logo.png
    - assets/logooo.png
    - assets/logo1.png
    - assets/prob.pdf
    - assets/probabilites.pdf
    - assets/grammaire.pdf
    - assets/spach.png